{"trial_id": "0", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "num_of_layers", "default": null, "conditions": [], "min_value": 2, "max_value": 20, "step": 1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "num_of_neurons0", "default": null, "conditions": [], "min_value": 50, "max_value": 100, "step": 1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "num_of_neurons1", "default": null, "conditions": [], "min_value": 50, "max_value": 100, "step": 1, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "learning_rate", "default": 0.01, "conditions": [], "values": [0.01, 0.001, 0.0001], "ordered": true}}, {"class_name": "Int", "config": {"name": "num_of_neurons2", "default": null, "conditions": [], "min_value": 50, "max_value": 100, "step": 1, "sampling": "linear"}}], "values": {"num_of_layers": 3, "num_of_neurons0": 56, "num_of_neurons1": 88, "learning_rate": 0.01, "num_of_neurons2": 50}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"D:\\anaconda3\\Lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 274, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\anaconda3\\Lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 239, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"D:\\anaconda3\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"D:\\anaconda3\\Lib\\site-packages\\keras_tuner\\src\\engine\\tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n  File \"D:\\anaconda3\\Lib\\site-packages\\keras_tuner\\src\\engine\\hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n           ~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"D:\\anaconda3\\Lib\\site-packages\\keras\\src\\utils\\traceback_utils.py\", line 122, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"D:\\anaconda3\\Lib\\site-packages\\keras\\src\\backend\\tensorflow\\nn.py\", line 734, in sparse_categorical_crossentropy\n    raise ValueError(\n    ...<3 lines>...\n    )\nValueError: Argument `output` must have rank (ndim) `target.ndim - 1`. Received: target.shape=(None, 26), output.shape=(None, 10)\n"}